// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	middleware "github.com/go-openapi/runtime/middleware"
	mock "github.com/stretchr/testify/mock"

	weather "github.com/nikulnik/weather/restapi/operations/weather"
)

// WeatherHandler is an autogenerated mock type for the WeatherHandler type
type WeatherHandler struct {
	mock.Mock
}

// GetWeather provides a mock function with given fields: params
func (_m *WeatherHandler) GetWeather(params weather.GetWeatherParams) middleware.Responder {
	ret := _m.Called(params)

	var r0 middleware.Responder
	if rf, ok := ret.Get(0).(func(weather.GetWeatherParams) middleware.Responder); ok {
		r0 = rf(params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(middleware.Responder)
		}
	}

	return r0
}
