// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// Forecast forecast
//
// swagger:model Forecast
type Forecast struct {

	// date
	Date string `json:"date,omitempty"`

	// humidity
	Humidity string `json:"humidity,omitempty"`

	// pressure
	Pressure string `json:"pressure,omitempty"`

	// sunrise
	Sunrise string `json:"sunrise,omitempty"`

	// sunset
	Sunset string `json:"sunset,omitempty"`

	// temperature
	Temperature string `json:"temperature,omitempty"`

	// wind
	Wind string `json:"wind,omitempty"`

	// wind speed
	WindSpeed string `json:"wind_speed,omitempty"`
}

// Validate validates this forecast
func (m *Forecast) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *Forecast) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Forecast) UnmarshalBinary(b []byte) error {
	var res Forecast
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
